name: movie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  fancy_shimmer_image: ^2.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.4
  get: 4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
